name: hackerspace_game_jam_2024
description: A basic game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.6
  go_router: ^12.0.1
  logging: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  vector_math: ^2.1.4
  flutter_shaders: ^0.1.2
  flame: ^1.14.0
  flame_forge2d: ^0.16.0+4
  equatable: ^2.0.5
  image: ^4.1.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.3
  animated_text_kit: ^4.2.2

flutter:
  uses-material-design: true

  shaders:
    - shaders/raymarching.frag
    - shaders/raymarching2d.frag

  assets:
    - assets/images/
    - assets/images/character/
    - assets/images/enemy/
    - assets/images/background/
    - assets/music/
    - assets/sfx/
    - assets/levels/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon-adaptive-foreground.png"
