{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 resolution;\nuniform shader spheres;\nuniform half2 spheres_size;\n\nvec4 fragColor;\n\nfloat radius;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    radius = 30.0 / resolution.x;\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / vec2(resolution.x);\n    vec4 color = vec4(1.0);\n    for (int i = 0; i < 256; i++)\n    {\n        vec4 sphere = spheres.eval(spheres_size *  vec2(float(i) / 256.0, 0.0));\n        if (sphere.w == 0.0)\n        {\n            continue;\n        }\n        vec2 pos = vec2(sphere.z, sphere.y);\n        vec2 distance = abs(pos - uv);\n        if (length(distance) < radius)\n        {\n            color = vec4(1.0, 0.0, 0.0, 1.0);\n        }\n    }\n    fragColor = color;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 2,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "resolution",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 0,
      "columns": 1,
      "location": 1,
      "name": "spheres",
      "rows": 1,
      "type": 12
    }
  ]
}